### PR TITLE
 fix(update_expected)!: remove unreported subtests a la tests 

### PR DESCRIPTION
**Pull request by ErichDonGubler**
This is something I forgot to do while implementing `process-reports`/`update-expected` originally! Oops. 😳 Mozilla had accumulated ~55k lines of metadata that it didn't need because this hadn't been implemented yet.

I've observed that `wptrunner` may not report subtests in `wptreport.json` artifacts in some cases while running CTS. This may cause some noise in folks' existing Try runs (i.e., deletions), and we might need to make this an option later, if the problems aren't easy to resolve.

### CODE REVIEW

**Comment by ErichDonGubler** [comment]
@sagudev, you'll probably be interested in this. It may clear out a significant amount of metadata for you, and it might cause some noise for you (see OP).

**Comment by sagudev** [comment]
> Mozilla had accumulated ~55k lines of metadata that it didn't need because this hadn't been implemented yet

This are subtest that got changed (renamed, removed, more sub options or whatever changes their name), right?

> I've observed that wptrunner may not report subtests in wptreport.json

This is alarming, but I have a hunch that the problem is in cts rather than in wptrunner. It will be interesting to see how this affects servo.

Tnx for the heads up, this reminds me that I should work on https://github.com/ErichDonGubler/moz-webgpu-cts/issues/106, but something always comes up in servo 😭.

**Comment by ErichDonGubler** [comment]
@sagudev:

> This are subtest that got changed (renamed, removed, more sub options or whatever changes their name), right?

Yep, that's right!

> This is alarming, but I have a hunch that the problem is in cts rather than in wptrunner. It will be interesting to see how this affects servo.

🤔 Let's tag @kainino, then, just in case they've heard of something of the sort! For your convenience, Kai, we're referring to this in the OP:

> I've observed that `wptrunner` may not report subtests in `wptreport.json` artifacts in some cases. This may cause some noise in folks' existing Try runs, and we might need to make this an option later, if the root cause isn't easy to resolve.

**Comment by ErichDonGubler** [comment]
CC @jimblandy, @teoxoy, @nical, who will likely be reviewing a patch against `mozilla-central` later in response to this change. 😛

**Comment by sagudev** [comment]
> wptrunner may not report subtests in wptreport.json artifacts in some cases

Do you have any concrete example or are they random?

**Comment by kainino0x** [comment]
My first thought would be that we're reporting completion to tesharness.js before we finish all the tests. I am pretty sure this is handled correctly but it could be buggy. I've had trouble using the testharness.js interface before.

If you can reproduce the issue I'd greatly appreciate if you can investigate a bit, or file a bug with repro steps.

**Comment by ErichDonGubler** [comment]
@sagudev, @kainino0x: I have some concrete examples, but I'll have to see if I can make them smaller and remember more details; the time I saw it was when a test with a texture format parameter reported `TIMEOUT`.

I'll file an issue in this tracker for follow-up.

**Comment by ErichDonGubler** [comment]
Filed <https://github.com/ErichDonGubler/moz-webgpu-cts/issues/137>.

**Pull request merged**
